CREATE TABLE [dbo].[Events]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Type] VARCHAR(1) NOT NULL,
	[Description] VARCHAR(50) NOT NULL,
	[BarCode] VARCHAR(13) NOT NULL,
	[StartDate] DATETIME NOT NULL DEFAULT GETDATE(), 
	[EndDate] DATETIME NOT NULL,
	[FkBarId] INT NOT NULL,
	FOREIGN KEY (FkBarId) REFERENCES Bars(Id)
)
